### ISSUE TITLE
2nd Milestone requirements

### ISSUE THREAD

**Issue by Kayeeec** [Richardb953/Airport-Manager#38]
- create facade interfaces and implement them
    - [ ] `AirportFacade`, `AirportFacadeImpl` - @xkrejci7 
    - [x] `AirplaneFacade`, `AirplaneFacadeImpl` - @Kayeeec
    - [ ] `FlightFacade`, `FlightFacadeImpl` - @Richardb953 
    - [ ] `StewardFacade`, `StewardFacadeImpl` - @andrea-n 
- create DTOs
    - [ ] `AirportDTO` - @xkrejci7 
    - [x] `AirplaneDTO` - @Kayeeec
    - [ ] `FlightDTO` - @Richardb953 
    - [ ] `StewardDTO` - @andrea-n 
- when any exception is thrown on DAO layer, `DataAccessException` or its subclass is thrown by **service layer**
    - [ ] `AirportServiceImpl` - @xkrejci7 
    - [x] `AirplaneServiceImpl` - @Kayeeec
    - [ ] `FlightServiceImpl` - @Richardb953 
    - [ ] `StewardServiceImpl` - @andrea-n 
- implement simple unit tests for facade layer. Just one simple test per method is enough. This is mainly so that it’s easy to verify the Facade layer works;
    - [ ] `AirportFacadeImplTest` - @andrea-n  
    - [ ] `AirplaneFacadeImplTest` - @Richardb953 
    - [ ] `FlightFacadeImplTest` - @xkrejci7  
    - [x] `StewardFacadeImplTest` - @Kayeeec
- There must be extensive unit tests for the service layer (particularly for your 2 business functions) and all the tests of service layer must use Mock DAO objects;
    - [ ] `AirportServiceImplTest` - @andrea-n 
    - [ ] `AirplaneServiceImplTest` - @Richardb953 
    - [ ] `FlightServiceImplTest` - @xkrejci7 
    - [x] `StewardServiceImplTest` - @Kayeeec
